# version format
version: "{branch}-{build}"

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Build on x64 only
platform: x64

environment:
  SFDX_AUTOUPDATE_DISABLE: true
  SFDX_DOMAIN_RETRY: 300

install:
  - echo 'hello world'
  - echo %SFDX_CI_DEVHUB_USERNAME%
 
